### ISSUE TITLE
public registries

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapphub-registry#7]
Since this code is public as well as dapple is, it is easy for anyone to deploy and use an own registry. So I assume people will be doing this because:
1. We are restricting the namespaces
2. They want to use private/ corporate packages
3. They want custom functionality in their registries

This got me thinking if we want to provide this as a standard feature:

Requirements: 
1. Dapple don't has one registry, but a hierarchy of registries for each environment.
2. The default registry is our root registry
3. Registries are specified in the `.dapplerc` ordered by their priority:
```
  live:
    ethereum:
      host: 192.168.59.103
      port: '8545'
    ipfs:
      host: localhost
      port: '5001'
    registries:
      - 0x0123...ef
      - 0xfe...3210
```
4. `dapple install <path> [<version>]` searches for the specified package beginning with the highest priority registry to the lowest, if a match is fount it is installed
4.1. `--registry (<address> | nr)` flag can be
5. `dapple publish` pushes always to the top registry unless a `--registry` flag is  given

This could lead to wider and quicker mass adoption of dapple and packages.

@nmushegian @ryepdx
